function PBE_Figure(X1, Y1, Y2, Y3, Y4, len_t)
global t figure1
%CREATEFIGURE(X1,Y1,Y2,Y3,Y4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  Y4:  vector of y data
%  Auto-generated by MATLAB on 15-Oct-2012 23:17:30

% % Create figure
% figure1 = figure;
% 
% % Create axes
% axes('Parent',figure1,'YTickLabel','','YTick',zeros(1,0),...
%     'YColor',[0.8 0.8 0.8],...
%     'XTickLabel','',...
%     'XTick',zeros(1,0),...
%     'XColor',[0.8 0.8 0.8],...
%     'Position',[0.099 0.08269 0.8595 0.8145],...
%     'CLim',[0 1]);
% 
% % Create title
% title(['Population Density of T-cells for CD3 Protein',sprintf('\n'),'Comparison of Analytical solution with MOC, Lax-Wendroff FDM'],...
%     'FontSize',12);
% 
% % Create xlabel
% xlabel('State variable "c_1"','FontSize',16,'Color',[0 0 0]);
% 
% % Create ylabel
% ylabel('Population Density','FontSize',16,'Color',[0 0 0]);

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.1391 0.5678 0.3529 0.2815]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'MarkerSize',3,'Marker','x',...
    'DisplayName','MOC');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Position',[0.2185 0.7401 0.1786 0.04002]);
title(['t= ',sprintf('%d',t(len_t(1)))]);

% Create axes
axes2 = axes('Parent',figure1,'Position',[0.5946 0.5679 0.3536 0.2816]);
box(axes2,'on');
grid(axes2,'on');
hold(axes2,'all');

% Create plot
plot(X1,Y2,'Parent',axes2,'MarkerSize',3,'Marker','x','Color',[0 1 0],...
    'DisplayName','MOC');
title(['t= ',sprintf('%d',t(len_t(2)))]);

% Create legend
legend2 = legend(axes2,'show');
set(legend2,'Position',[0.6694 0.7396 0.1786 0.04002]);

% Create axes
axes3 = axes('Parent',figure1,'Position',[0.1338 0.1692 0.3573 0.3088]);
box(axes3,'on');
grid(axes3,'on');
hold(axes3,'all');

% Create plot
plot(X1,Y3,'Parent',axes3,'MarkerSize',3,'Marker','x','Color',[1 0 1],...
    'DisplayName','MOC');

% Create legend
legend3 = legend(axes3,'show');
set(legend3,'Position',[0.1551 0.4116 0.1786 0.04002]);
title(['t= ',sprintf('%d',t(len_t(3)))]);

% Create axes
axes4 = axes('Parent',figure1,'Position',[0.592 0.1722 0.3562 0.3074]);
box(axes4,'on');
grid(axes4,'on');
hold(axes4,'all');

% Create plot
plot(X1,Y4,'Parent',axes4,'MarkerSize',3,'Marker','x',...
    'DisplayName','MOC',...
    'Color',[0 0 0]);

% Create legend
legend4 = legend(axes4,'show');
set(legend4,'Position',[0.5919 0.4168 0.1786 0.04002]);
title(['t= ',sprintf('%d',t(len_t(4)))]);

